### PR TITLE
Numeric Array Formula and Matrix Function Patch Applied

### PR DESCRIPTION
**Pull request by Bob95132**
Follow up to the request for pull request format of patch

### CODE REVIEW

**Comment by pjfanning** [comment]
I have added the test xlsx file and added the ant and gradle build changes necessary for commons-math3 at https://github.com/Bob95132/poi/pull/1 - would you be able to merge these to your branch?

**Comment by Bob95132** [comment]
I apologize for the late response and thank you for those corrections. Should I supply a new patch including these changes to bugzilla or is the pull request sufficient? Is another pull request to Apache/POI needed?

**Comment by pjfanning** [comment]
We can use this Pull Request and your existing github branch while we review this change.
We are in the middle of releasing 3.17 and we need to decide whether to include this.
Would you be able to fix the broken tests?

**Comment by Bob95132** [comment]
For clarification, correcting the failed tests in TestWorkbookEvaluator? Did this error occur during a full system JUnit run and were there other failures?

**Comment by pjfanning** [comment]
the tests in TestWorkbookEvaluator fail in the IDE or if you run them using `ant clean test` - the NullPointerException happens in code that you are adding

**Comment by Bob95132** [comment]
I have fixed the broken tests. Please let me know if there is anything else I can do.

**Comment by pjfanning** [comment]
I see another test failure:
  <testcase classname="org.apache.poi.xssf.usermodel.TestXSSFDataValidation" name="testTableBasedValidationList" time="0.093">
    <failure message="wrong # of valid values expected:&lt;32&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: wrong # of valid values expected:&lt;32&gt; but was:&lt;0&gt;
	at org.apache.poi.xssf.usermodel.TestXSSFDataValidation.testTableBasedValidationList(TestXSSFDataValidation.java:354)

**Comment by pjfanning** [comment]
Would it also be possible to add some tests for an xls file (HSSF format)?

**Comment by Bob95132** [comment]
Im working on the TestXSSFDataValidation and will make an xls file test suite. I have noticed that test suites between xls and xlsx are sometimes duplicated. Is it sufficient to keep the test cases within the workbook the same?

**Comment by pjfanning** [comment]
running similar tests is fine - it's just that we need to have an xls input file as well as an xlsx - the test classes themselves should be separate - one for HSSF and one for XSSF

**Comment by Bob95132** [comment]
Thanks for the clarification

**Comment by Bob95132** [comment]
I have added the tests for the HSSFWorkbook and corrected the failure that was occurring with TestXSSFDataValidation. Please let me know the next steps in evaluating this contribution.

**Comment by pjfanning** [comment]
We're in the process of releasing 3.17. I will look at merging this once it is released.

**Comment by mzdravkov** [comment]
Hello, what is the status of this MR? Is there any chance it'll be merged soon?

**Comment by pjfanning** [comment]
merged on Sep 14, 2017

**Pull request closed without merging**
