### PR TITLE
WIP: xmlbeans 3.0.0

### PR DESCRIPTION
**Pull request by pjfanning**
uses the xmlbeans 3.0.0 release candidate

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/56/

**Comment by pjfanning** [comment]
run tests

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/58/

**Review by centic9 — APPROVED** [review]

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/59/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/60/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/61/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/62/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/63/

**Pull request closed without merging**
