### PR TITLE
Fixed text search error.

### PR DESCRIPTION
**Pull request by zhangfugui727**
### Such as:
Search `${code}` in Runs data `["code:${", "code","}"]`.
The correct result returned should be
```
### start
startRun 0
startText 0
startChar 5
### end
endRun 2
endText 0
endChar 0
```
But the actual interior only retains the ```startRun``` state, and ```startText, startChar``` are reset at each loop.
```
startRun 0
startText 0
startChar 0
```

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by zhangfugui727** [comment]
> Can one of the admins verify this patch?

For the first time in this library, I don't know how to provide a code example, but it works.

**Review by pjfanning — CHANGES_REQUESTED** [review]
I'm afraid we'll need a test case or a good description of the issue before we can proceed.
Could you open a ticket on https://bz.apache.org/bugzilla/ for discussion?

**Comment by zhangfugui727** [comment]
@pjfanning Ok, thanks for the guidance.

**Comment by zhangfugui727** [comment]
@pjfanning [https://bz.apache.org/bugzilla/show_bug.cgi?id=62779](https://bz.apache.org/bugzilla/show_bug.cgi?id=62779)

`src/ooxml/java/org/apache/poi/xwpf/usermodel/XWPFParagraph.java`

Each loop of `rArray` in the `searchText` method causes `beginTextPos` and `beginCharPos` to be reset accordingly. The resulting `TextSegment` returns invalid data.

**Comment by jhny** [comment]
If somebody stumbles upon this bug/PR. Note that it seem to be merged in the 4.1.0 release of POI.

**Comment by pjfanning** [comment]
@jhny this change is not merged to POI trunk

**Comment by jhny** [comment]
Yeah sorry my bad it's not, been staring at this thing a little too long.

**Comment by centic9** [comment]
Unfortunately this was closed by some automated job, but we cannot reopen it ourselves, please reopen if this is still an active PR so it does not get lost.

**Pull request closed without merging**
