### PR TITLE
Super sxssf

### PR DESCRIPTION
**Pull request by mobreza**
Rebased MR https://github.com/apache/poi/pull/141 on master.

### CODE REVIEW

**Comment by mobreza** [comment]
@pjfanning This is to resume discussions and figure out if this code is still useful since it's a year since the previous MR.

**Comment by pjfanning** [comment]
This code does not compile

**Comment by pjfanning** [comment]
* `protected ISheetInjector createSheetInjector(InputStream xis) throws IOException` is now correct
* I don't like the SuperSXSSF names, can we use EmittingSXSSF instead?

The workbook constructor does not compile but this does

```
    public EmittingSXSSFWorkbook(XSSFWorkbook workbook, int rowAccessWindowSize) {
        super(workbook, rowAccessWindowSize, false, false);
    }
```

**Comment by pjfanning** [comment]
Thanks. Merged with https://github.com/apache/poi/commit/f06c45421b1904f196f6aa4c2f99989a1f3185c6

We can treat this as beta for now, as I expect that we might need to add some checks to handle edge cases.

**Comment by mobreza** [comment]
I'll check our existing code that uses this extension. What's the URL of the maven SNAPSHOTS repository?

**Comment by pjfanning** [comment]
when https://builds.apache.org/view/P/view/POI/job/POI-DSL-1.8/1011/ completes - check https://builds.apache.org/view/P/view/POI/job/POI-DSL-1.8/lastSuccessfulBuild/artifact/

**Comment by mobreza** [comment]
Thanks, will have a look. I was expecting it at https://repository.apache.org/content/groups/snapshots.

**Comment by pjfanning** [comment]
https://github.com/mobreza/poi/pull/1#issuecomment-650729604 provides an example of how to use code (except the `SuperSXXSF` classes are renamed as `EmittingSXXSF`

**Comment by pjfanning** [comment]
@mobreza I'm struggling to think of a good name for these classes. SuperSXSSF was too vague but EmittingSXSSF is not right either. How about DeferredSXSSF or LazySXSSF because of the fact that the actual generation of the rows is delayed until you start writing to the output stream?

**Comment by mobreza** [comment]
Migration from 3.17 (!) to 5.0.0-SNAPSHOT required renaming the `SuperSXSSF*` to `EmittingSXSSF*` and some minor updates: https://gitlab.croptrust.org/genesys-pgr/genesys-server/-/compare/master...apache-poi-5.0.0-SNAPSHOT

I didn't experience any problems with generating Excel files. Downloads start immediately and canceling the download request results in ending the database scan:

```
07:06:04,435 qtp1795970853-260  WARN o.g.s.s.i.DownloadServiceImpl:277 - Writing Excel to output stream
07:06:08,744 qtp1795970853-260  WARN o.g.s.s.i.DownloadServiceImpl:206 - Error generating: org.eclipse.jetty.io.EofException
07:06:08,749 qtp1795970853-260  WARN o.g.s.a.v.AccessionController:553 - Download was aborted: Closed
```

Our code uses [templates](https://gitlab.croptrust.org/genesys-pgr/genesys-server/-/compare/master...apache-poi-5.0.0-SNAPSHOT#e6dd878cf3275b5e86d2c89ce08d0fa9c0291a93_227_226) and [blank workbooks](https://gitlab.croptrust.org/genesys-pgr/genesys-server/-/compare/master...apache-poi-5.0.0-SNAPSHOT#e6dd878cf3275b5e86d2c89ce08d0fa9c0291a93_227_226).

**Comment by pjfanning** [comment]
Renamed the classes in https://github.com/apache/poi/commit/9f8b864c413bb3418e79a15172e7d2aac10ee12e

**Pull request closed without merging**
