### PR TITLE
[bug-62018] use ints to index fonts

### PR DESCRIPTION
**Pull request by pjfanning**
With 4.0.0 being the next release, it seems like we can make relatively large changes like using ints for indexing fonts (instead of shorts).
Ideally, it would be good to have a test case for https://bz.apache.org/bugzilla/show_bug.cgi?id=62108

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/40/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/41/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/42/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/43/

**Comment by pjfanning** [comment]
https://svn.apache.org/viewvc?view=revision&revision=1824826

**Pull request closed without merging**
