### PR TITLE
XDDF merge test with #62092

### PR DESCRIPTION
**Pull request by kiwiwings**
This is just a merge test to synchronize my local svn repo.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by Alain-Bearez** [comment]
The content of `cuali:xddf-text` is now ready for code review and merging.

**Comment by pjfanning** [comment]
LGTM

**Comment by Alain-Bearez** [comment]
merged with commit r1839259

**Comment by pjfanning** [comment]
@Alain-Bearez would you be able to look at the compile issues? http://apache-poi.1045710.n5.nabble.com/Build-failed-in-Jenkins-POI-DSL-1-8-509-td5731471.html

**Comment by Alain-Bearez** [comment]
Sorry!  

I merged wrong branch…

**Comment by Alain-Bearez** [comment]
This pull request can now be closed as the code has been merged and released in 4.0.0

**Comment by kiwiwings** [comment]
ignore me ...

**Pull request closed without merging**
