### PR TITLE
Add ReadingOrder support for XSSFCellStyle

### PR DESCRIPTION
**Pull request by irafishbein**
This support already exists for HSSFCellStyle, so just added the same logic for XSSFCellStyle

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by tomerm** [comment]
@ADIR01 / @SEMION1956 FYI.

**Comment by irafishbein** [comment]
@Gagravarr
I am not sure who can take a look at this codechange. 
Can you, please? In case you can't - can you please advise me who can?
Thank you,
Ira

**Comment by centic9** [comment]
I took a quick look, one question in general: 

Is the long-value useful outside of POI at all? Or is it rather something that is only needed internally in the on-disk format? 

Maybe we can just remove the setter/getter which set/get "long" and only provide the enum to the outside to keep the interface simple?

**Comment by irafishbein** [comment]
@centic9 
Thank you very much for looking at it.
I've added mentioned setters/getters to make API similar to an existing one in HSSFCellStyle.
Please let me know if you still believe they should be removed.
Thank you.

**Comment by centic9** [comment]
I have pushed a slightly modified version of the patch which only adds setter/getter for the enum-value. I see no use in providing the long-value to the outside and we probably should switch to the Enum for HSSF as well in the future and deprecate the "short" versions there.

Please close this PR if the change is sufficient for you or comment if you think this should be done differently.

**Comment by irafishbein** [comment]
@centic9 
Thank you, the change looks ok.
Can you please explain me when this change is expected to be part of 'official' build?

**Comment by tomerm** [comment]
@centic9 , answering the "when" question would be great. However I realize that it might be problematic and in any case it would be only tentative. Yet, if you can say in which **version** of POI it will be present for sure it would help a lot. For example, any chances it can make it into 7.10 ?  Many thanks.

**Comment by centic9** [comment]
When is probably hard to say as we currently do not follow a defined release-timeline, release version will be 4.0, which we started to work on 2 months ago, a release typically happens every few months, so early 2018 would be a rough guess.

**Pull request closed without merging**
