### PR TITLE
fix: when copy slide,new slide use old textrun object reference

### PR DESCRIPTION
**Pull request by FlyingPigQAQ**

### CODE REVIEW

**Comment by pjfanning** [comment]
Please provide some description - and ideally a test case to go with this. It is not enough to modify code without describing why.

**Comment by pjfanning** [comment]
It is also better to raise a bug first before providing PRs. See https://bz.apache.org/bugzilla

**Comment by FlyingPigQAQ** [comment]
> It is also better to raise a bug first before providing PRs. See https://bz.apache.org/bugzilla

Hello, I read the buglist and found an issue with the same problem but not fixed. The address is as follows. https://bz.apache.org/bugzilla/show_bug.cgi?id=65473

**Comment by FlyingPigQAQ** [comment]
Unit tests were added.

**Comment by pjfanning** [comment]
merged - thanks

**Pull request closed without merging**
