### PR TITLE
Fixes #62242

### PR DESCRIPTION
**Pull request by shamohao**
1. Fixes issue #62242：Had an incorrect bonus 0 on the end when number format is "??" and value
is 0. 
2. Found another bug on new test case. That bug is unrelated with this fix. I have made a TODO on that test case.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by pjfanning** [comment]
Thanks for the patch. I ran the unit tests and there is at least one failure.
`ant clean test`

    [junit] Running org.apache.poi.ss.format.TestCellFormatPart
    [junit] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.207 sec

```
  <testcase classname="org.apache.poi.ss.format.TestCellFormatPart" name="testNumberApproxFormat" time="0.026">
    <error message="Cannot find numer in &quot;| 123456.789 |e| |&quot;" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Cannot find numer in &quot;| 123456.789 |e| |&quot;
	at org.apache.poi.ss.format.TestCellFormatPart.extractNumber(TestCellFormatPart.java:158)
	at org.apache.poi.ss.format.TestCellFormatPart.access$000(TestCellFormatPart.java:34)
	at org.apache.poi.ss.format.TestCellFormatPart$3.equivalent(TestCellFormatPart.java:95)
	at org.apache.poi.ss.format.CellFormatTestBase.tryColor(CellFormatTestBase.java:246)
	at org.apache.poi.ss.format.CellFormatTestBase.tryFormat(CellFormatTestBase.java:220)
	at org.apache.poi.ss.format.CellFormatTestBase.runFormatTests(CellFormatTestBase.java:128)
	at org.apache.poi.ss.format.TestCellFormatPart.testNumberApproxFormat(TestCellFormatPart.java:85)
</error>
  </testcase>
```

**Review by pjfanning — CHANGES_REQUESTED** [review]
Need to fix tests

**Comment by centic9** [comment]
OK to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/4/

**Pull request closed without merging**
