### PR TITLE
Xmlbeans 2.6.5

### PR DESCRIPTION
**Pull request by pjfanning**
I'm suggesting that we use xmlbeans fork in POI 4.0.0 while we consider the options around replacing xmlbeans or coming up with a better way of maintaining xmlbeans.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/25/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/27/

**Comment by centic9** [comment]
Looks technically good, but let's discuss/vote on the dev-list before merging this.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/28/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/29/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/30/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/33/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/44/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/45/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-Github-PullRequests/47/

**Pull request closed without merging**
