### PR TITLE
Define XDDF user model for shape properties to be shared between XSLF, XSSF and XWPF

### PR DESCRIPTION
**Pull request by Alain-Bearez**
The main goal of this work is to provide a user model API in order to handle the shape properties without using underlying XmlBeans objects and interfaces. Among others, handling properties related to colors is made simpler by returning and accepting an abstract XDDFColor, which has six distinct implementations, where the developers were required to check whether or not one of the six properties was set.

What is left to be done:
- refactor XSLFColor to make use of the new shareable code;
- deprecate methods that return XmlBeans objects where a user model object now exists.

### CODE REVIEW

**Comment by centic9** [comment]
Testing Github->Jenkins integration: run tests

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by centic9** [comment]
FYI, CI on this branch failed with

```
compile-ooxml:
    [javac] Compiling 524 source files to /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/build/ooxml-classes
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFValueAxis.java:56: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(getOrAddLinesProperties(majorGridlines));
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFValueAxis.java:67: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(getOrAddLinesProperties(minorGridlines));
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFValueAxis.java:78: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(properties);
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFCategoryAxis.java:56: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(getOrAddLinesProperties(majorGridlines));
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFCategoryAxis.java:67: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(getOrAddLinesProperties(minorGridlines));
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFCategoryAxis.java:79: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(properties);
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFDateAxis.java:60: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(getOrAddLinesProperties(majorGridlines));
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFDateAxis.java:71: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(getOrAddLinesProperties(minorGridlines));
    [javac]                ^
    [javac] /home/jenkins/jenkins-slave/workspace/POI-Github-PullRequests/src/ooxml/java/org/apache/poi/xddf/usermodel/chart/XDDFDateAxis.java:82: error: XDDFShapeProperties(CTShapeProperties) has protected access in XDDFShapeProperties
    [javac]         return new XDDFShapeProperties(properties);
```

See https://builds.apache.org/job/POI-Github-PullRequests/3/console

**Comment by Alain-Bearez** [comment]
passing tests locally

**Comment by Alain-Bearez** [comment]
@centic9 Sorry for the unfortunate push breaking the compilation.
Since your previous attempt to run the tests, I continued to push work on both branches.

I thought you would first review #68 in order to have a somewhat easier code review before reviewing this additional work. Also consider a third chunk is underway, trying to unify text paragraphs and text runs from both XSLF and XSSF since they both rely on the same DrawingML but none of them can correctly handle text from chart legend entries.

**Comment by pjfanning** [comment]
@Alain-Bearez the changes generally look good but would it be possible to add more unit tests?

**Comment by Alain-Bearez** [comment]
It would be a bunch of tests for getters and setters... 

I will try to find some time before the end of the year to copy and adapt the tests from `TestXSLFColor` and `TestXSSFColor` which are also mainly testing getters and setters.

**Comment by pjfanning** [comment]
@Alain-Bearez If this is ready to merge, I can go ahead and do that.

**Comment by Alain-Bearez** [comment]
@pjfanning I was only waiting for Dominik to confirm that the integration tests are passing for that branch.

**Comment by centic9** [comment]
Build-Results: https://builds.apache.org/view/P/view/POI/job/POI-Github-PullRequests/26/

**Pull request closed without merging**
