### PR TITLE
org.apache.poi.xwpf.converter.core.XWPFConverterException: java.lang.NullPointerException  

### PR DESCRIPTION
**Pull request by tuean**
version : 3.15.
I try to remove all tableRows by using XWPFTable  table.removeRow();
And then, in  computeColWidths of class XWPFTableUtil,
Param firstRow(Line 66) was returnd by getFirstRow() and the value was null,
so when the code runs to line 97 and step into getNbColumnsToIgnore(firstRow, true),
it will throw NullPointerException
Beg for someone who knows these apis well and fix this problem,thx!

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by onealj** [comment]
Please rebase your pull request.

**Review by onealj — CHANGES_REQUESTED** [review]
Github shows this pull request as containing over 3000 changed files. Please rebase, close and open a new correctly-based PR, or attach a diff/patch to bugzilla, whichever is easiest for you. It's difficult for devs to try to find the changes you made buried inside such a large PR.

**Comment by onealj** [comment]
org.apache.poi.xwpf.converter isn't part of POI's package structure. POI doesn't have a method called "getNbColumnsToIgnore". This issue is filed under the wrong product. This closes #82.

**Pull request closed without merging**
