### PR TITLE
Share chart data implementation between XSSFChart and XSLFChart through XDDF

### PR DESCRIPTION
**Pull request by Alain-Bearez**
The main goal of this work is to be able to:
  - duplicate a slide that has a chart on it (https://bz.apache.org/bugzilla/show_bug.cgi?id=57835);
  - more easily access definitions for axes;
  - more easily set data series for axes;
  - share code between XSLF and XSSF: XSSFChart and XSLFChart are using XDDFChartData.

What is left to be done:
  - complete implementation of first five chart types;
  - implement other chart types.

### CODE REVIEW

**Comment by aperrot42** [comment]
A shame I decided to go with docx4j to implement a higher level charting library for pptx... We would have had a lot of common code to share.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Review by onealj — APPROVED** [review]
Skimming through the changes, looks good to me. I think this is a good idea!

**Comment by Alain-Bearez** [comment]
@onealj After this pull request will have been merged, I suggest you continue your review on the next PR related to XDDF: #72 

The third PR about XDDF is not ready yet.

**Comment by onealj** [comment]
This PR looks good and ready to merge. We should probably have you sign a contributor license agreement before merging. I sent an email to your cua.li address with details.

**Comment by centic9** [comment]
CI also is green on commit de37f95113fb4226ef70bd050cde101b71d4c0a3, see https://builds.apache.org/view/P/view/POI/job/POI-Github-PullRequests/7/

**Pull request closed without merging**
