### PR TITLE
int2String string2int

### PR DESCRIPTION
**Pull request by helloworld2688**
when string to int, use Math.pow will cost much time
when int to string ,not use StringBuilder, will produce much string chip, yet cost much time

### CODE REVIEW

**Comment by Gagravarr** [comment]
Thanks for the patch! I've committed slightly modified versions in r1516983, along with unit tests.

**Comment by helloworld2688** [comment]
:) where can i find the r1516983 , i can not fount it in github or git://git.apache.org/poi.git

**Comment by Gagravarr** [comment]
Web view is http://svn.apache.org/viewvc?view=revision&revision=1516983 or just ask your svn client for it on http://svn.apache.org/repos/asf/poi/trunk

**Comment by helloworld2688** [comment]
wonderful :)

**Pull request closed without merging**
