### PR TITLE
#62865 solves/unifies blank/missing value colection for PRODUCT/MDETERM/GEOMEAN 

### PR DESCRIPTION
**Pull request by gallonfizik**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Review by pjfanning — COMMENTED** [review]
LGTM - could you resync with trunk?

**Comment by gallonfizik** [comment]
@pjfanning what do you mean? For all I see, latest trunk (6ac20d5) is merged into this branch, and this page shows no conflicts.

**Comment by gallonfizik** [comment]
@pjfanning for the future: https://bz.apache.org/bugzilla/show_bug.cgi?id=62875#c1 sounds reasonable?

**Review by pjfanning — APPROVED** [review]

**Comment by pjfanning** [comment]
https://svn.apache.org/repos/asf/poi/trunk@1849237

**Pull request closed without merging**
