### PR TITLE
fix REL_4_1_0-CORE_PROPERTIES_ECMA376 error

### PR DESCRIPTION
**Pull request by RealBlackCat**
fix REL_4_1_0 CORE_PROPERTIES_ECMA376 error

### CODE REVIEW

**Comment by pjfanning** [comment]
A couple of things:
* this 4.1.0 branch is unsupported
* we prefer PRs to have test cases

**Comment by RealBlackCat** [comment]
> A couple of things:
> 
> * this 4.1.0 branch is unsupported
> * we prefer PRs to have test cases

Can you tell me the version maintained now? I have the same problem when testing 5.0.0.
This problem will be repeated only when a specific docx is saved all the time. I don't know how to write its test cases

**Comment by pjfanning** [comment]
trunk is the main branch

**Comment by pjfanning** [comment]
I committed https://github.com/apache/poi/commit/981b1ccf033eeb291c6a915cdd6a04958b2f111b and will see if this causes any build/test issues

**Comment by pjfanning** [comment]
@RealBlackCat can you close this Pull Request?

**Comment by RealBlackCat** [comment]
> @RealBlackCat can you close this Pull Request?

ok

**Comment by pjfanning** [comment]
I reverted my change - see https://github.com/apache/poi/commit/8649a4672c8b092dfe2330df254612719f037181 - the original value matches the Microsoft specification doc - https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/db9b9b72-b10b-4e7e-844c-09f88c972219

**Pull request closed without merging**
