### PR TITLE
improve MAPIMessage.guess7BitEncoding, improve MAPIMessage.getHtmlBody

### PR DESCRIPTION
**Pull request by dhoelzl**
improve MAPIMessage.guess7BitEncoding

 - general properties code page sources: PR_MESSAGE_CODEPAGE, default ANSI code page of PR_MESSAGE_LOCALE_ID, charset from content-type header
 - code page source for PR_BODY and PR_BODY_HTML: PR_INTERNET_CPID (as documented)
   no need to get from HTML; Outlook skips that too
   special case: outlook uses code page CP1252 instead of utf-8 for PR_BODY

improve MAPIMessage.getHtmlBody:

 - in case if binary property use code page defined in PR_INTERNET_CPID, default to CP1252 (no need to get from HTML; Outlook skips that too)
 - in case of string property rely on code page set by MAPIMessage.guess7BitEncoding

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Review by pjfanning — COMMENTED** [review]
Do you have any sample files to try the new code on? If so, can you use them in unit tests (for regression purposes)?

**Comment by dhoelzl** [comment]
I have added a unit test to the PR.

**Comment by pjfanning** [comment]
Closed using https://github.com/apache/poi/commit/721180d35f2777c38a7d8206b5d1555a82f92acb

**Pull request closed without merging**
