### PR TITLE
Add AREAS function

### PR DESCRIPTION
**Pull request by 101hanbin**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Review by pjfanning — CHANGES_REQUESTED** [review]
We'll need good test coverage before we accept this pull request

**Comment by 101hanbin** [comment]
I'm done

**Comment by 101hanbin** [comment]
You can find it

**Comment by pjfanning** [comment]
Could you remove the eclipse project changes?

**Comment by 101hanbin** [comment]
Yes,I can

**Comment by 101hanbin** [comment]
I'm done

**Review by pjfanning — APPROVED** [review]

**Comment by 101hanbin** [comment]
Can it be merged so that I don’t have to see it every day

**Pull request closed without merging**
