### PR TITLE
Rel 2 branch

### PR DESCRIPTION
**Pull request by malangalanga**

### CODE REVIEW

**Comment by onealj** [comment]
REL_2_BRANCH is an out-of-date, unmaintained branch. This squashed pull request has tree conflicts due to reorganizing POI for Common SS and Common SL.

Please read https://poi.apache.org/guidelines.html#Submitting+Patches for guidelines for submitting patches. Patches or pull requests should be small, reviewable, focused, with unit tests.

This pull request should be put on hold or rejected.

**Review by onealj — CHANGES_REQUESTED** [review]
Why is this a pull request? REL_2_BRANCH is old.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by gmcdonald** [comment]
closing this PR as branch is to be deleted .See INFRA-17285

**Pull request closed without merging**
