### PR TITLE
#59388 - Set comment with option isVisible in `.xlsx`

### PR DESCRIPTION
**Pull request by ryoii**
Fix the bug reported from https://bz.apache.org/bugzilla/show_bug.cgi?id=59388

### CODE REVIEW

**Comment by pjfanning** [comment]
@ryoii thanks but could you add a test case for this?

**Comment by ryoii** [comment]
I deleted my fork repo a few days ago. I am going to make a new pull request with test cases. But now I cant run the project I forked. 

```
A problem occurred configuring root project 'poi'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'Bstek(http://nexus.bsdn.org/content/groups/public/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.1/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 
```

I add the property `allowInsecureProtocol` in the `repositories` but it doesn't work. How i can fix it?

**Comment by ryoii** [comment]
I run unit test with gradle error like
```
Could not write standard input to Gradle Test Executor 1.
java.io.IOException: The pipe is being closed
```

How i can fix it?

**Comment by pjfanning** [comment]
@ryoii can you provide the full output when the gradle command fails? Can you include the gradle command itself? For instance, are you using gradlew command?

**Comment by ryoii** [comment]
@pjfanning Yep, I run with gradlew 

`gradlew :poi-ooxml:test --scan --tests "org.apache.poi.xssf.usermodel.TestXSSFComment.bug57838DeleteRowsWthCommentsBug"`

And there is the log
```
Welcome to Gradle 7.1!

Here are the highlights of this release:
 - Faster incremental Java compilation
 - Easier source set configuration in the Kotlin DSL

For more details see https://docs.gradle.org/7.1/release-notes.html

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Trying to override old definition of datatype junit
Could not write standard input to Gradle Test Executor 1.
java.io.IOException: The pipe is being closed
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)

> Task :poi-ooxml:test FAILED
Error occurred during initialization of boot layer
java.nio.file.InvalidPathException: Illegal char <:> at index 35: ../build/dist/maven/poi-ooxml-tests:E:\code\poi\build\dist\maven\poi-scratchpad

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':poi-ooxml:test'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights
.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 20s
40 actionable tasks: 25 executed, 15 up-to-date

```

**Comment by pjfanning** [comment]
Looks like there is a bug in build.gradle that prevents tests from running on Windows. I committed a change just now. I don't use Windows so I'm not able to test it.

**Comment by ryoii** [comment]
> Looks like there is a bug in build.gradle that prevents tests from running on Windows. I committed a change just now. I don't use Windows so I'm not able to test it.

it works

**Comment by ryoii** [comment]
My original fork repo has been deleted, I open a new pr instead #239

**Pull request closed without merging**
