### PR TITLE
Adding a wrapper to evaluate all xssf formula cells "in cell"

### PR DESCRIPTION
**Pull request by sawyna**
There is `XSSFFormulaEvaluator.evaluateAllFormulaCells` already present. But that doesn't remove the formulas from the cells. This wrapper loops over all the cells in all sheets in the workbook, calls `evaluateInCell` which removes the formulas from the cells containing formulas and puts the result.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by sawyna** [comment]
Hi, can any one please verify this and merge?

**Comment by pjfanning** [comment]
@sawyna could you describe the issue you are trying to fix?
If this seems worth merging, it will need unit test coverage.

**Comment by sawyna** [comment]
There is no wrapper util method to evaluate all formulas in the workbook, replace the formulas with the evaluated values. This pull request tries to address the same

**Comment by centic9** [comment]
Unfortunately this was closed by some automated job, but we cannot reopen it ourselves, please reopen if this is still an active PR so it does not get lost.

**Comment by sawyna** [comment]
@centic9 How do I re-open the PR? I don't seem to get an option anywhere.

**Comment by centic9** [comment]
It seems the GitHub repo is somehow broken as also the diff of the PR is not available any more, so the safest option for now would be to create bug-entry at https://bz.apache.org/bugzilla/ and attach a patch there.

**Pull request closed without merging**
