### PR TITLE
Fixed issue where a zero length libre office document with a water mark ...

### PR DESCRIPTION
**Pull request by rojotek**
...image was causing an identifier out of range bug.
#### What's this PR do?

Changes the min value for the identifier manager in XWPFDocument to be 0, as the included test document had an identifier with value 0.

Document Sourced from libre office with a watermark and no text.

The newly added testcase will fail if the code change is removed.

### CODE REVIEW

**Comment by Gagravarr** [comment]
Any chance you could update the unit test to also check that we correctly found the image in the header?

**Comment by rojotek** [comment]
how does that look @Gagravarr ?

**Comment by Gagravarr** [comment]
Is it worth also asserting that the text of the header is empty, do you think?

Also, I've just noticed the naming of things like `getHeaderArray(int)` which looks a bit odd to me, so I've started a thread on the dev list about it. Your opinion there would be helpful!

**Comment by rojotek** [comment]
Asserting that the text is empty probably makes sense (so have coded it up :) ).

**Comment by Gagravarr** [comment]
Purely style changes, but were it me:
- Might be good to put all the properties checks together
- Would probably be easier to read if you fetched the XWPFHeader once, then used that everywhere you check, rather than calling `doc.getHeaderArray(0)` each time

**Comment by rojotek** [comment]
was that what you had in mind?

**Comment by Gagravarr** [comment]
Perfect, thanks! Committed in r1661908.

**Comment by rojotek** [comment]
Commited through svn and in trunk so closing this PR.

**Pull request closed without merging**
