### PR TITLE
Seven more XDDF charts and bug fixes

### PR DESCRIPTION
**Pull request by Alain-Bearez**
The code in this pull request builds on code from Sandeep Tiwari in https://github.com/apache/poi/pull/144

Some code formatting and code patterns have been improved, as well as some light improvements in overall functionalities.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/13/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/14/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/21/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/24/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/25/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/27/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/POI-DSL-Github-PullRequests/28/

**Comment by Alain-Bearez** [comment]
applied as r1859590

**Comment by lycfr** [comment]
image
hello，poi:4.1.0 Display errors for more than one bar chart. you can see photo

**Pull request closed without merging**
