### PR TITLE
PropertiesChunk.writeProperties: no need to write ASCII_STRING properties as UNICODE_STRING

### PR DESCRIPTION
**Pull request by dhoelzl**
PropertiesChunk.writeProperties: no need to write ASCII_STRING properties as UNICODE_STRING as written raw value (PropertyValue.getRawValue) is formatted as ASCII_STRING

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by pjfanning** [comment]
@dhoelzl could you open a discussion on the POI dev list? https://poi.apache.org/help/index.html - or raise a bugzilla issue

**Comment by pjfanning** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=63447

**Review by pjfanning — COMMENTED** [review]
Do you have a sample file to test this code on? If so, could you use it in a unit test?

**Comment by dhoelzl** [comment]
I have created a unit test to verify this.

**Comment by centic9** [comment]
Unfortunately this was closed by some automated job, but we cannot reopen it ourselves, please reopen if this is still an active PR so it does not get lost.

**Pull request closed without merging**
