### PR TITLE
Update XWPFHeaderFooterPolicy.java

### PR DESCRIPTION
**Pull request by souhaib100**
Add case when there is already header in the docx.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Review by pjfanning — COMMENTED** [review]
Thanks. Would it be possible to add a test case?

**Comment by souhaib100** [comment]
Where?

**Comment by pjfanning** [comment]
maybe in poi/src/ooxml/testcases/org/apache/poi/xwpf/usermodel/TestXWPFHeader.java

Tests can be with `ant clean test`

**Comment by centic9** [comment]
Unfortunately this was closed by some automated job, but we cannot reopen it ourselves, please reopen if this is still an active PR so it does not get lost.

**Pull request closed without merging**
